### ISSUE TITLE
Can someone explain me how I can make kakuja form like Eto or Kakujira from RoGhoul in Roblox Studio? I don't know how to write a script. I need that I can activate it on key 1,2,3 and etc

### ISSUE THREAD

**Issue by damm1Dam** [Emancyphur/Roblox-Studio-Tutorials#3]

**Comment by Emancyphur** [comment]
I'm sorry, but I am not familiar with that game. As a starting point, you can detect User Input with [`UserInputService.InputBegan`](https://create.roblox.com/docs/reference/engine/classes/UserInputService#InputBegan), which returns an [`InputObject`](https://create.roblox.com/docs/reference/engine/classes/InputObject). You can then check the [`KeyCode`](https://create.roblox.com/docs/reference/engine/classes/InputObject#KeyCode) property of the `InputObject` to see if it matches any of the keys that the player would need to press in order to activate that ability / power / etc.

Here's a quick example:

```lua
local UserInputService = game:GetService("UserInputService")

local abilityKeyCodes = {
    [1] = Enum.KeyCode.One,
    [2] = Enum.KeyCode.Two,
    [3] = Enum.KeyCode.Three
}

local function activateAbility(number)
-- There are other ways of implementing this, but this might be more intuitive to understand, to start
    if number == 1 then
        -- Run code related to the ability that should be activated with the "1" key
    elseif number == 2 then
        -- Run code related to the ability that should be activated with the "2" key
    elseif number == 3 then
        -- Run code related to the ability that should be activated with the "3" key
    end
end

UserInputService.InputBegan:Connect(function(inputObject, interactedWithUI)
    if interactedWithUI == true then return end

    local keyCode = inputObject.KeyCode
    local abilityCheck = table.find(abilityKeyCodes, keyCode)

    if abilityCheck then
        activateAbility(abilityCheck)
    end
end)
```

---

For future reference, this isn't the correct category for these kinds of questions. The "Issues" section of this repository is meant for highlighting issues with the code, models, etc. of my tutorials that have been posted here. If you have a suggestion for a future tutorial, you can post that in the Discussions category / section.

However, the question you asked here might be better suited for the [Roblox Developer Forum](https://devforum.roblox.com/). There are probably some existing threads on the Developer Forum where people have asked similar questions that were eventually solved, which might be able to help with answering your question(s) much faster than I'd be able to, especially since I don't know much about the game that you referenced.
